name: Scheduled GitHub Analysis

on:
  schedule:
    # 每天 UTC 时间 00:00 运行
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # 根据需要调整 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-bigquery requests pandas tqdm

    - name: Authenticate to GCP
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Create results directory
      run: mkdir -p result

    - name: Run BigQuery and GitHub Analysis
      run: |
        python main.py
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Commit and push results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add result/
        git commit -m "Add new analysis results for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push